# Generated by Django 6.0.6 on 2026-06-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_code',
            field=models.CharField(choices=[('ESP', 'Espanol'), ('ENG', 'Ingles'), ('FRA', 'Frances'), ('POR', 'Portugues'), ('ITA', 'Italiano')], default='ESP', max_length=3),
        ),
    ]
