# Generated by Django 6.0.6 on 2026-06-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
