# Generated by Django 6.0.6 on 2026-06-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='action_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='company_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='contact_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='request_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='request_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
