# Generated by Django 6.0.6 on 2026-06-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_audittrail_action_type_audittrail_changes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audittrail',
            options={'ordering': ['-performed_at'], 'verbose_name': 'Traza de Auditoría', 'verbose_name_plural': 'Trazas de Auditoría'},
        ),
    ]
