# Generated by Django 6.0.6 on 2026-06-19 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('temperature_set_point', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity_set_point', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('packaging_description', models.CharField(blank=True, max_length=255)),
                ('company_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SamplingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('tolerance_days', models.PositiveIntegerField(default=0)),
                ('recalculated_date', models.DateField(blank=True, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_points', to='stability.study')),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_code', models.CharField(max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('received', 'Received'), ('labelled', 'Labelled'), ('in_chamber', 'In chamber'), ('extracted', 'Extracted'), ('analysed', 'Analysed'), ('destroyed', 'Destroyed'), ('blocked', 'Blocked')], default='received', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('placed_in_chamber_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('chamber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='stability.chamber')),
                ('sampling_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='stability.samplingpoint')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='stability.study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChamberDeviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('impact_assessment', models.TextField(blank=True)),
                ('requires_recalculation', models.BooleanField(default=False)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='stability.chamber')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations', to='stability.study')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
