# Generated by Django 6.0.6 on 2026-06-19 14:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamberLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('room', models.CharField(blank=True, max_length=255)),
                ('shelf', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackagingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('presentation', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('dosage_form', models.CharField(blank=True, max_length=100)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('company_code', models.CharField(default='AGQ', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('temperature_set_point', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity_set_point', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('light_condition', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='current_stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sample',
            name='label_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chamber',
            name='chamber_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chambers', to='stability.chamberlocation'),
        ),
        migrations.AddField(
            model_name='study',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='stability.packagingconfiguration'),
        ),
        migrations.AddField(
            model_name='study',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studies', to='stability.product'),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('manufactured_at', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_released', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('packaging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='stability.packagingconfiguration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stability.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='study',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studies', to='stability.productbatch'),
        ),
        migrations.CreateModel(
            name='SampleReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reception_number', models.CharField(max_length=50, unique=True)),
                ('received_from', models.CharField(blank=True, max_length=255)),
                ('received_by', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to='stability.productbatch')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='stability.study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='stability.samplereception'),
        ),
        migrations.CreateModel(
            name='StabilityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stability.sample')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stability.study')),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('reception', 'Reception'), ('label', 'Label'), ('chamber_in', 'Chamber in'), ('extraction', 'Extraction'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity_delta', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='stability.sample')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddField(
            model_name='chamber',
            name='storage_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chambers', to='stability.storagecondition'),
        ),
    ]
