# Generated by Django 6.0.6 on 2026-06-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stability', '0002_chamberlocation_packagingconfiguration_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('study_type', models.CharField(blank=True, max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('condition_code', models.CharField(blank=True, max_length=50)),
                ('format_name', models.CharField(blank=True, max_length=100)),
                ('color_hex', models.CharField(default='#DCEBFF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='container',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='physical_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='shelf',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='tray',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='samplereception',
            name='discrepancy_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='samplereception',
            name='quantity_assigned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='samplereception',
            name='quantity_contingency',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='samplereception',
            name='quantity_expected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='samplereception',
            name='quantity_reserved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sample',
            name='label_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='stability.labeltemplate'),
        ),
    ]
