# Generated by Django 6.0.6 on 2026-06-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stability', '0003_labeltemplate_sample_container_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamber',
            options={'verbose_name': 'Cámara', 'verbose_name_plural': 'Cámaras'},
        ),
        migrations.AlterModelOptions(
            name='chamberdeviation',
            options={'verbose_name': 'Desviación de Cámara', 'verbose_name_plural': 'Desviaciones de Cámaras'},
        ),
        migrations.AlterModelOptions(
            name='chamberlocation',
            options={'verbose_name': 'Ubicación de Cámara', 'verbose_name_plural': 'Ubicaciones de Cámaras'},
        ),
        migrations.AlterModelOptions(
            name='labeltemplate',
            options={'verbose_name': 'Plantilla de Etiqueta', 'verbose_name_plural': 'Plantillas de Etiquetas'},
        ),
        migrations.AlterModelOptions(
            name='packagingconfiguration',
            options={'verbose_name': 'Configuración de Acondicionamiento', 'verbose_name_plural': 'Configuraciones de Acondicionamiento'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productbatch',
            options={'verbose_name': 'Lote de Producto', 'verbose_name_plural': 'Lotes de Productos'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Muestra', 'verbose_name_plural': 'Muestras'},
        ),
        migrations.AlterModelOptions(
            name='samplereception',
            options={'verbose_name': 'Recepción de Muestra', 'verbose_name_plural': 'Recepciones de Muestras'},
        ),
        migrations.AlterModelOptions(
            name='samplingpoint',
            options={'ordering': ['target_date'], 'verbose_name': 'Punto de Muestreo', 'verbose_name_plural': 'Puntos de Muestreo'},
        ),
        migrations.AlterModelOptions(
            name='stabilityalert',
            options={'ordering': ['status', 'due_date', '-created_at'], 'verbose_name': 'Alerta de Estabilidad', 'verbose_name_plural': 'Alertas de Estabilidad'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-executed_at'], 'verbose_name': 'Movimiento de Stock', 'verbose_name_plural': 'Movimientos de Stock'},
        ),
        migrations.AlterModelOptions(
            name='storagecondition',
            options={'verbose_name': 'Condición de Almacenamiento', 'verbose_name_plural': 'Condiciones de Almacenamiento'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['-created_at'], 'verbose_name': 'Estudio de Estabilidad', 'verbose_name_plural': 'Estudios de Estabilidad'},
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('received', 'Recibida'), ('labelled', 'Etiquetada'), ('in_chamber', 'En camara'), ('extracted', 'Extraida'), ('analysed', 'Analizada'), ('destroyed', 'Destruida'), ('blocked', 'Bloqueada')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='samplereception',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('received', 'Recibida'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stabilityalert',
            name='severity',
            field=models.CharField(choices=[('info', 'Informativa'), ('warning', 'Advertencia'), ('critical', 'Critica')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='stabilityalert',
            name='status',
            field=models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('reception', 'Recepcion'), ('label', 'Etiquetado'), ('chamber_in', 'Entrada en camara'), ('extraction', 'Extraccion'), ('adjustment', 'Ajuste')], max_length=20),
        ),
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('closed', 'Cerrado')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='SampleSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_date', models.DateField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='stability.sample')),
            ],
            options={
                'verbose_name': 'Fecha de Muestreo',
                'verbose_name_plural': 'Fechas de Muestreo',
                'ordering': ['planned_date', 'id'],
            },
        ),
    ]
