# Generated by Django 6.0.6 on 2026-06-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stability', '0005_client_study_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagingconfiguration',
            options={'verbose_name': 'Formato', 'verbose_name_plural': 'Formatos'},
        ),
        migrations.AddField(
            model_name='sampleschedule',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
