# Generated by Django 6.0.6 on 2026-06-27 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stability', '0014_samplereception_batch_number_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingPointTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_number', models.PositiveIntegerField(unique=True)),
                ('label', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Maestro Punto de Muestreo',
                'verbose_name_plural': 'Maestros Puntos de Muestreo',
                'ordering': ['month_number'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanningEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_type', models.CharField(choices=[('fq', 'FQ'), ('micro', 'Micro')], max_length=20)),
                ('subsample_quantity', models.PositiveIntegerField(default=0)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_entries', to='stability.chamber')),
                ('sampling_point_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_entries', to='stability.samplingpointtemplate')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_entries', to='stability.study')),
            ],
            options={
                'verbose_name': 'Linea de Planificacion',
                'verbose_name_plural': 'Lineas de Planificacion',
                'ordering': ['sampling_point_template__month_number', 'chamber__code', 'analysis_type'],
                'constraints': [models.UniqueConstraint(fields=('study', 'sampling_point_template', 'chamber', 'analysis_type'), name='unique_study_planning_entry')],
            },
        ),
    ]
