# Generated by Django 6.0.6 on 2026-06-27 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stability', '0015_samplingpointtemplate_studyplanningentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedSubsample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_type', models.CharField(choices=[('fq', 'FQ'), ('micro', 'Micro')], max_length=20)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('actual_sampling_date', models.DateField(blank=True, null=True)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('location_notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('in_chamber', 'En camara'), ('withdrawn', 'Retirada')], default='in_chamber', max_length=20)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_subsamples', to='stability.chamber')),
                ('sampling_point_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_subsamples', to='stability.samplingpointtemplate')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_subsamples', to='stability.study')),
            ],
            options={
                'verbose_name': 'Submuestra Planificada',
                'verbose_name_plural': 'Submuestras Planificadas',
                'ordering': ['sampling_point_template__month_number', 'code'],
            },
        ),
    ]
