# Generated by Django 6.0.6 on 2026-06-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stability', '0016_plannedsubsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedsubsample',
            name='label_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plannedsubsample',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plannedsubsample',
            name='storage_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
